title: NormalLLer's Page
description: Welcome to NormalLLer's GitHub Page!

baseurl: "/guidelines"
# theme: just-the-docs
remote_theme: pmarsceill/just-the-docs

url: https://normalller.github.io/

aux_links:
  My GitHub Profile: https://github.com/NormalLLer

aux_links_new_tab: true

heading_anchors: true

plugins:
  - jekyll-default-layout

footer_content: "Copyright &copy; NormalLLer. Distributed by an <a href=\"https://github.com/NormalLLer/NormalLLer.github.io/blob/main/LICENSE\">MIT license.</a>"

# last_edit_timestamp: true
# last_edit_time_format: "%b %e %Y at %I:%M %p"

color_scheme: light