title: NormalLLer's Blog
description: Welcome to NormalLLer's GitHub Blog!
theme: just-the-docs

url: https://normalller.github.io/

aux_links:
  Template Repository: https://github.com/NormalLLer/NormalLLer.github.io

plugins:
  - jekyll-default-layout
